### ISSUE TITLE
Loss of ability to conda index using threads

### ISSUE THREAD

**Issue by t-bltg** [conda/conda-package-handling#13]
Currently, the use of conda index with multiple threads triggers issues with libarchive. 

This is due to the fact that `os.chdir` in `utils.tmp_chdir` changes the global process working directory, not the local thread working directory.

A dirty fix which allows threaded indexing:
```diff
--- conda_package_handling/tarball.py  2019-05-18 12:56:00.224167806 +0200
+++ conda_package_handling/tarball.py  2019-05-18 18:22:15.569657793 +0200
@@ -67,15 +67,18 @@
 
 
 def _tar_xf(tarball, dir_path):
-    flags = libarchive.extract.EXTRACT_TIME | \
-            libarchive.extract.EXTRACT_PERM | \
-            libarchive.extract.EXTRACT_SECURE_NODOTDOT | \
-            libarchive.extract.EXTRACT_SECURE_SYMLINKS | \
-            libarchive.extract.EXTRACT_SECURE_NOABSOLUTEPATHS
     if not os.path.isabs(tarball):
         tarball = os.path.join(os.getcwd(), tarball)
-    with utils.tmp_chdir(dir_path):
-        libarchive.extract_file(tarball, flags)
+
+    flags = (
+        'extract.EXTRACT_TIME | '
+        'extract.EXTRACT_PERM | '
+        'extract.EXTRACT_SECURE_NODOTDOT | '
+        'extract.EXTRACT_SECURE_SYMLINKS | '
+        'extract.EXTRACT_SECURE_NOABSOLUTEPATHS'
+    )
+    cmd = [sys.executable, '-c', "from libarchive import extract_file, extract; extract_file('%s', %s)" % (tarball, flags)]
+    subprocess.run(cmd, cwd=dir_path)
 
 
 class CondaTarBZ2(AbstractBaseFormat):
```

@msarahan I've just seen the rework of // indexing in conda-build `3.18.1`, however, I believe the root issue is `conda-package-handling` not being thread friendly ...

**Comment by msarahan** [comment]
That is certainly what it boils down to, I agree.  I'm not sure about your subprocess fix here, though.  I'm concerned about the overhead.  I guess we should do some benchmarks.  No sense in worrying without actual numbers to worry about.

**Comment by mingwandroid** [comment]
I'd prefer to add a function to libarchive and submit it upstream.
