### ISSUE TITLE
Miscellaneous code style issues

### ISSUE THREAD

**Issue by travishathaway** [conda/conda-package-handling#155]
### What is the idea?

For conda projects, it is preferred to use spelled out rather than abbreviated variable names. We need to clean up this project to make sure that we are following this rule.

Another this project has is inconsistent string interpolation methods. The entire project should be using f-string format.

### Why is this needed?

Implementing these fixes will help boost the overall code quality and readability.

### What should happen?

- [ ] Replace `kw` with `kwargs`
- [ ] Replace `fn` with `filename`
- [ ] Replace `pkg` with `package`
- [ ] Make sure all string interpolation is using f-strings
- [ ] Remove any unused imports

**Comment by dholth** [comment]
Do we have a code style policy document to link to
