### ISSUE TITLE
Add pre-commit hooks to this project

### ISSUE THREAD

**Issue by travishathaway** [conda/conda-package-handling#156]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

This project is now under the conda organization and should be using the same linters and code formatters as `conda` and `conda-build`.

### Why is this needed?

We need to make sure that we have consistent code style and quality across all conda organization projects.

### What should happen?

- [ ] Copy over the existing pre-commit hooks from the `conda` project.

**Comment by dholth** [comment]
See https://github.com/conda/conda-package-handling/blob/main/.pre-commit-config.yaml
