### ISSUE TITLE
NameError: name '_Executor' is not defined. Did you mean: 'executor'?

### ISSUE THREAD

**Issue by bollwyvl** [conda/conda-package-handling#164]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

trying to `cph verify` a `.conda` created by https://github.com/conda-forge/kubo-feedstock/pull/6 (available from [azure](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=617179&view=artifacts&pathAsName=false&type=publishedArtifacts))

```
 Traceback (most recent call last):
  File "~/mf/bin/cph", line 11, in <module>
    sys.exit(main())
  File "~/mf/lib/python3.10/site-packages/conda_package_handling/cli.py", line 159, in main
    failed_files = api.verify_conversion(
  File "~/mf/lib/python3.10/site-packages/conda_package_handling/api.py", line 161, in verify_conversion
    with _Executor(max_workers=processes) as executor:
NameError: name '_Executor' is not defined. Did you mean: 'executor'?
```

### Conda Info

```shell
active environment : ~/projects/deathbeds/condoit/.venv
    active env location : ~/projects/deathbeds/condoit/.venv
            shell level : 4
       user config file : ~/.condarc
 populated config files : ~/mf/.condarc
          conda version : 22.9.0
    conda-build version : 3.22.0
         python version : 3.10.6.final.0
       virtual packages : __cuda=11.4=0
                          __linux=5.15.0=0
                          __glibc=2.35=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : ~/mf  (writable)
      conda av data dir : ~/mf/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : ~/mf/pkgs
                          ~/.conda/pkgs
       envs directories : ~/mf/envs
                          ~/.conda/envs
               platform : linux-64
             user-agent : conda/22.9.0 requests/2.27.1 CPython/3.10.6 Linux/5.15.0-52-generic ubuntu/22.04.1 glibc/2.35
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
```


### Conda Config

```shell
==> ~/mf/.condarc <==
channels:
  - conda-forge
```

### Conda list

```shell
it's kinda dirty, here's `^conda`:


conda                     22.9.0          py311h38be061_2    conda-forge
conda-build               3.22.0          py311h38be061_3    conda-forge
conda-lock                1.2.1              pyhd8ed1ab_1    conda-forge
conda-pack                0.7.0              pyh6c4a22f_0    conda-forge
conda-package-handling    1.9.0           py311hd4cff14_1    conda-forge
conda-standalone          4.12.0               ha770c72_0    conda-forge
```
```


### Additional Context

underlying issue is a failure to upload a `.conda` recipe from azure CI: https://github.com/conda-forge/kubo-feedstock/issues/5

**Comment by jakirkham** [comment]
Looks like that line got removed in PR ( https://github.com/conda/conda-package-handling/pull/130 ) as part of `2.0.0`

**Comment by dholth** [comment]
@bollwyvl You might not love the fix: we removed the verify subcommand entirely.

There is a better function to do the verification: https://github.com/conda/conda-package-handling/blob/main/src/conda_package_handling/validate.py#L59

New cph transmute should always run archives through that function before exiting, though the error reporting is a little weird consisting of concatenated exception strings? and may not exit(0) / exit(1)? All preserved as faithfully as possible from 1.x for compatibility.

**Comment by bollwyvl** [comment]
Yeah, dunno... as a user, getting on the `.conda` boat has been a bit bumpy... my `go`-related build is still failing:

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=621012&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802

with the recently-discussed-on-gitter:

```
zstd.ZstdError: zstd compress error: Allocation error : not enough memory
```

**Comment by dholth** [comment]
All will be fixed Thursday.

**Comment by jakirkham** [comment]
Yep tried to summarize in comment ( https://github.com/conda-forge/kubo-feedstock/issues/5#issuecomment-1332891870 )

**Comment by jakirkham** [comment]
Also linking the Windows OOM issue ( https://github.com/conda/conda-package-handling/issues/167 )

**Comment by dholth** [comment]
Moot in 2.x series.
