### ISSUE TITLE
Add `conda` subcommand

### ISSUE THREAD

**Issue by jakirkham** [conda/conda-package-handling#165]
When calling this from other environments, it would be helpful to have a `conda` subcommand. Maybe something like `conda package-handling` (given `conda package` is already taken).

**Comment by dholth** [comment]
We have the new plugin API.

I think the current conda-package-handling API does some things (like list of files vs. file containing a list of files, depending on what type is passed) better left to the cli parser, and taken out of the API. There are other peculiarities specific to the `cph` tool like #145
