### ISSUE TITLE
Change default zstd-compress-level to 19

### ISSUE THREAD

**Issue by dholth** [conda/conda-package-handling#168]
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

#167 shows that our current default compression level of -22 (from the command line, guarded behind `zstd --ultra`) uses 600+ MB. -19, the highest non-ultra level, uses a little less than 100MB and will be faster to compress. Maybe the default level should be 19, or even a lower amount.

**Comment by jezdez** [comment]
I think it can't hurt to lower the default to 19 now and investigate further if a further decrease makes sense.

**Comment by dholth** [comment]
However it's conda-build setting 22 unfortunately.

**Comment by jezdez** [comment]
True, gotta get https://github.com/conda/conda-build/pull/4661 out

**Comment by dholth** [comment]
Pretty sure we have one default level in the api and a second one in the cli parsing that should be updated

**Comment by dholth** [comment]
#169
