### ISSUE TITLE
Reproducing cph created tarballs

### ISSUE THREAD

**Issue by wolfv** [conda/conda-package-handling#179]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I've tried a bit to bit-for-bit reproduce the `.tar.bz2` files that `cph` produces (using libarchive from C++).

One difference that I found is that the `mtime` is stored as a `float` (?) in the Python-produced `.tar.bz2` file while the `libarchive` one is storing it as a integer. Additionally, dthe Python version adds a PAX header while libarchive doesn't:

```
mtime 1648738260.0 1648738260
Pax headers: {'mtime': '1648738260.0'} {}
```

I tried a bit to hack around but couldn't yet figure out how to change this. 

Another thing that might be adjusted (on the C++ size) is the block size for the compression, idk.

**Comment by wolfv** [comment]
Hmm, 

when I set the tar format to `USTAR`, it seems to produce more similar archives (not exactly similar yet):

```py
with tarfile.open(fullpath, "w:bz2", compresslevel=9, format=tarfile.USTAR_FORMAT) as t:
    ...
```

**Comment by wolfv** [comment]
Some other differences between libarchive and Python' `tarfile` is that Python zeroes out devmajor and devminor to `000000000` and `libarchive` still writes out `0` as a number which has a different representation.

**Comment by dholth** [comment]
I like PAX archives, but I'm surprised it would always add a PAX header, and not just when certain PAX features were being used. Another flag?

See also https://github.com/python/cpython/issues/80449 for some remarks on the benefits of PAX format
