### ISSUE TITLE
Symlink permissions handling for more reproducible builds

### ISSUE THREAD

**Issue by wolfv** [conda/conda-package-handling#185]
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

Apparently Linux only supports 0777 as permissions for symlinks (which is not the case on other unix, it's not specified in POSIX).

E.g. https://wiki.debian.org/ReproducibleBuilds/Howto#Symlinks_in_data.tar_contain_varying_file_mode

Should we try to always encode symlink permissions as 0777?

**Comment by dholth** [comment]
If we decided to do this, we could do it in https://github.com/conda/conda-package-handling/blob/main/src/conda_package_handling/utils.py#L486 or by overriding the chown method in TarFile on extract.

**Comment by wolfv** [comment]
We're making packages reproducible with rattler / rattler-build and are using the `deterministic` mode of the `tar` crate to make sure that permissions are encoded reproducibly.
