### ISSUE TITLE
conda-package-handling: conflicting version info in metadata - mix of 1.6.1 and 1.7.0

### ISSUE THREAD

**Issue by vx1920** [conda/conda-package-handling#64]
I have Anaconda with base environment only, I never did create additional "environments".
```
 conda version : 4.8.3
 conda-build version : 3.18.11
 python version : 3.7.7.final.0
```
 It seems to me I have problem with version of "conda-package-handling". I have version 1.7.0 in "dist-info" folder name and inside metadata file in this folder. At the same time I have 1.6.1 in the conda-meta/*.json filename and inside this json file and same 1.6.1 in pkgs. It did look bad and I did try to fix it. I did following dirty trick: manually remove dist-info, json and corresponding folder in pkgs. I did keep intact  "lib\site-packages\conda-package-handling" folder with all the code. After that I did run "conda install --force-reinstall  conda-package-handling".
It was completed OK, all metadata/pkgs reapper, but it has same conflicting version info.
What does it mean ? Can it be that somebody uses different version info in different places for some good reason, but I don't understand why they do it this way ?

**Comment by mingwandroid** [comment]
They are actually the same version, code-wise, the only difference is the dependencies. I should've made fully different version numbers though. I need to build 1.7.1 builds that will correct this and discuss whether we need to do anything with the old builds.

As far as I know, though, this should be harmless!

**Comment by vx1920** [comment]
It is good to hear that it is harmless. I did afraid that I did screw everything in my computer after updating pip-installed packages with conda or vice versa. Actually there are few more problems. Full report below, code in github. Maybe you can find even more mismatches in your computer, if you
care about it.

```
 --- Scan metadata for version mismatch ---
Prefix: d:\InstSoft\Python\Conda3x64
LibSP : d:\InstSoft\Python\Conda3x64\Lib\site-packages
conda-meta : d:\InstSoft\Python\Conda3x64\conda-meta
Version Mix:
  ['anaconda_project', '0.8.3', 'dist-info', 'LibSP']
  ['anaconda-project', '0.8.4', 'py_0', 'conda-meta']
Version Mix:
  ['conda_package_handling', '1.7.0', 'dist-info', 'LibSP']
  ['conda-package-handling', '1.6.1', 'py37h62dcd97_0', 'conda-meta']
Version Mix:
  ['pyodbc', '4.0.0_unsupported', 'dist-info', 'LibSP']
  ['pyodbc', '4.0.30', 'py37ha925a31_0', 'conda-meta']
Version Mix:
  ['setuptools', '47.1.1.post20200604', 'py3.7', 'egg-info', 'LibSP']
  ['setuptools', '47.1.1', 'py37_0', 'conda-meta']
Version mix in metadata for 4 package(s)
```
P.S.
While trying to understand what was installed by conda and what was by pip - I did create issue with with pip. They look at it and told me that it was especially "conda", who place garbage to metadata and they are not responsible for "pip list" reporting wrong information about "installer".
Can somebody from conda group to look to the https://github.com/pypa/pip/issues/8415
