### ISSUE TITLE
Test failures on arm-64

### ISSUE THREAD

**Issue by nileshpatra** [conda/conda-package-handling#74]
Hi,

conda-package-handling fails [this](https://github.com/conda/conda-package-handling/blob/master/tests/test_api.py#L186) test since the time is now past December 1, 2020.

If it still isn't fixed, do you think it'd be sensible to extend it to December 1, 2021?

**Comment by nileshpatra** [comment]
cc: @msarahan @mingwandroid

**Comment by mingwandroid** [comment]
Yes we'll have to bump it for now. PR welcome.

**Comment by nileshpatra** [comment]
@msarahan PR: #75 Please consider merging :-)

**Comment by nileshpatra** [comment]
@mingwandroid PR: #75 Please consider merging :-)

**Comment by mingwandroid** [comment]
Since there's no CLA in place for this repo, I will apply the same change and commit it myself. Sorry about that. The new release will come out ASAP though.
