### ISSUE TITLE
Directory symlinks not preserved when converting .tar.bz2 -> .conda

### ISSUE THREAD

**Issue by chenghlee** [conda/conda-package-handling#84]
conda-package-handling 1.7.3 is removing symlinks where the target is a directory when transmuting from `.tar.bz2` to `.conda` format.

A minimal recipe to replicate this issue:
```
# meta.yaml
package:
  name: test_symlink
  version: 0.0.1

# build.sh
mkdir -p "${PREFIX}/dir_a"
echo -n "" > "${PREFIX}/dir_a/a_file.txt"
ln -sn "${PREFIX}/dir_a/a_file.txt" "${PREFIX}/dir_a/b_file.txt"
ln -sn "${PREFIX}/dir_a" "${PREFIX}/dir_b"
```

Contents of `test_symlink-0.0.1-0.tar.bz2` (excluding the contents of `info/`):
```
lrwxrwxr-x  0 502    20          0 Nov 12 11:07 dir_b -> dir_a
lrwxrwxr-x  0 502    20          0 Nov 12 11:07 dir_a/b_file.txt -> a_file.txt
-rw-rw-r--  0 502    20          0 Nov 12 11:07 dir_a/a_file.txt
```

Contents of `pkg-test_symlink-0.0.1-0.tar` (note the missing `dir_b` symlink):
```
lrwxrwxr-x  0 502    20          0 Nov 12 11:07 dir_a/b_file.txt -> a_file.txt
-rw-rw-r--  0 502    20          0 Nov 12 11:07 dir_a/a_file.txt
```

This looks like #15 re-surfacing.

**Comment by chenghlee** [comment]
Marking as sev-1 because it's breaking [this workaround](https://github.com/AnacondaRecipes/python-feedstock/pull/47/files#diff-e0638ff31f64a715c0ed3faa90c7b9f61ef3ff28d4a622e89e31923e585394bbR511-R513) in Anaconda's `python=3.10` packages.

**Comment by msarahan** [comment]
It's getting filtered into the info tarball for whatever reason.

```
-> % cph x test_symlink-0.0.1-0.tar.bz2 
-> % cph c test_symlink-0.0.1-0 test_symlink-0.0.1-0.conda
-> % mkdir conda-fmt
-> % mv test_symlink-0.0.1-0.conda conda-fmt 
-> % cph x --info test_symlink-0.0.1-0.conda --prefix $(pwd)
-> % ls -la test_symlink-0.0.1-0
total 28
drwxrwxr-x 3 msarahan msarahan 4 Jan 28 14:11 .
drwxrwxr-x 3 msarahan msarahan 4 Jan 28 14:11 ..
lrwxrwxrwx 1 msarahan msarahan 5 Jan 28 13:52 dir_b -> dir_a
drwxrwxr-x 3 msarahan msarahan 9 Jan 28 14:11 info
-> % rm -rf test_symlink-0.0.1-0
-> % cph x test_symlink-0.0.1-0.conda --prefix $(pwd)
-> % ls -la test_symlink-0.0.1-0
total 37
drwxrwxr-x 4 msarahan msarahan 5 Jan 28 14:16 .
drwxrwxr-x 3 msarahan msarahan 4 Jan 28 14:16 ..
drwxrwxr-x 2 msarahan msarahan 4 Jan 28 14:16 dir_a
lrwxrwxrwx 1 msarahan msarahan 5 Jan 28 13:52 dir_b -> dir_a
drwxrwxr-x 3 msarahan msarahan 9 Jan 28 14:16 info

```

**Comment by tobijk** [comment]
This isn't fixed.

Steps to reproduce:

1. Create a clean Python environment with cph 1.8.0 installed
2. Download a recent Python 3.10.4 package
    `wget https://repo.anaconda.com/pkgs/main/linux-64/python-3.10.4-h12debd9_0.tar.bz2`
3. Convert the package to .conda
4. Unpack the original .tar.bz2 into subdirectory `orig/` and the converted package into `converted/`
5. Examine the contents of the lib directory

Notice how the symlink `lib/python3.1` is present in orig, but not in converted.
